import type { Metadata } from "next";

import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import TopSocialMedia from "@/components/TopSocialMedia";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { AuthContextProvider, ParallaxProviders } from "../components/Providers";
export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body
                className={cn(
                    "min-h-screen w-screen max-w-full overflow-x-hidden scroll-smooth bg-gray-900 font-montserrat antialiased flex flex-col",
                )}
            >
                {" "}
                <AuthContextProvider>
                    <TopSocialMedia />
                    <Navigation />

                    <ParallaxProviders>{children}</ParallaxProviders>

                    <Footer />
                </AuthContextProvider>
            </body>
        </html>
    );
}
